import icon_cd from "../Images/banner3.jpg";
const CourseDescFashion = [
  {
    id: 1,
    ServiceIcon: icon_cd,
    ServiceName: "B.SC in Fashion Design",
    Duration: "36 Months",
    Eligibility: "10th Grade",
    Slugs: "/fashion-design",
    ServicePara1:
      "This one is the premier degree program of Fashion Designing. During the program, you will develop an in-depth understanding of the tools and techniques which are used in Fashion Designing. You will be interacting with our Subject Matter Experts, who have worked on projects that have been acclaimed both nationally and internationally.",
      Mode:"Theory",
    First: [
      {
        Sno:"1",
       
        CName1:"Introduction to Fashion Designing(Theory)" , 
    },
    {
      Sno:"2",
      Mode:"Theory",
      CName1:"Component of Fashion Designing" , 
  },
  {
    Sno:"3",
    Mode:"Theory/Practical",
    CName1:"Embroidery" , 
},
{
  Sno:"4",
  Mode:"Theory/Practical",
  CName1:"Fashion Illustration" , 
},
{
  Sno:"5",
  Mode:"Theory/Practical",
  CName1:"Furnishing of Room" , 
},
{
  Sno:"6",
  Mode:"Theory/Practical",
  CName1:"Digital Marketing" , 
},
{
  Sno:"7",
  Mode:"Theory/Practical",
  CName1:"Surface Ornamentation" , 
},
{
  Sno:"8",
  Mode:"Theory/Practical",
  CName1:"Pattern Drafting" , 
},
{
  Sno:"9",
  Mode:"Theory/Practical",
  CName1:"Computer Fundamentals (Photoshop)" , 
},
{
  Sno:"10",
  Mode:"Theory/Practical",
  CName1:"History of Fashion" , 
},
{
  Sno:"11",
  Mode:"Theory/Practical",
  CName1:"Co-Curricular courses" , 
},

 ],
    Second: [
      
     {
      Sno:"1",
      Mode:"Theory",
      CName1: "Textile Science",
     },
     {
      Sno:"2",
      // Mode:"Theory",
      CName1: "Textile Designing",
     },
       { Sno:"3",
      //  Mode:"Theory/Practical",
       CName1: "Fashion Illustration",
      },
        
       {Sno:"4",
      //  Mode:"Theory/Practical",
        CName1: "Sustainability in Fashion industry",
      },
      {Sno:"5",
      // Mode:"Theory/Practical",
        CName1: "Design Technology",},

        
        {Sno:"6",
        // Mode:"Theory/Practical",
          CName1: "Garment Construction",},
        {Sno:"7",
        // Mode:"Theory/Practical",
          CName1: "Fashion Merchandising",},
        {Sno:"8",
        // Mode:"Theory/Practical",
          CName1: "Portfolio (English)",
        },
   
        {Sno:"9",
        // Mode:"Theory/Practical",
          CName1: "Digital & Technological Solutions (Photoshop)",
        },
        {Sno:"10",
        // Mode:"Theory/Practical",
          CName1: "Fine Applied Visual Arts" ,
        },
    ],
      Third: [
        {Sno:"1",
        Mode:"Theory",
        CName1: "Surface Ornamentation - II ",
      },
      {      Sno:"2",
        Mode:"",
          CName1: "Fashion Illustration - Croquis ( Kids & Female)  (Practical)",
    },
    {Sno:"3",
    Mode:"",
          CName1: "Garment Construction II (Practical)",
  },
  {Sno:"4",
  Mode:"Theory/Practical",
            CName1: "Textiles Manufacturing and Applications ",
},
{Sno:"5",
Mode:"Theory/Practical",
            CName1: "Textiles Manufacturing and Applications (Practical)",
},
{Sno:"6",
Mode:"Theory/Practical",
          CName1: "Digital Photography ",
},
{Sno:"7",
Mode:"Theory/Practical",
          CName1: "Fashion Illustration - Corel Draw (Practical)",
},
{Sno:"8",
Mode:"Theory/Practical",
          CName1: "Modern Indian Languages - Hindi & Marathi",
        },
        {Sno:"9",
Mode:"Theory/Practical",
          CName1: "Co-curricular activities",
        },
        {Sno:"10",
Mode:"Theory/Practical",
          CName1: "Field Project - Fashion Designing ",
        },
      ],
      Fourth: [
        // {
        //   Sno:"1",
        // Mode:"Theory",
        // },
        {Sno:"1",
        Mode:"Theory",
          CName1: "Fashion Illustration - Croquis ( Mens & Bridal)",
      },
      {
        Sno:"2",
        Mode:"Theory",
          CName1: "Advance Corel Draw",
      },
      {Sno:"3",
      Mode:"Theory/Practical",
          CName1: "Advance Garment Construction",
    },
 
  {Sno:"4",
  Mode:"Theory/Practical",
              CName1: "Fashion Forecasting & Draping mannequins",
},{Sno:"5",
Mode:"Theory/Practical",
          CName1: "Grooming",
},
{Sno:"6",
Mode:"Theory/Practical",
          CName1: "Yarn Craft",
},
{Sno:"7",
Mode:"Theory/Practical",
          CName1: "Modern Indian Languages 2 ",
},
{Sno:"8",
Mode:"Theory/Practical",
          CName1: "Co-curricular activities",
        },
        {Sno:"9",
Mode:"Theory/Practical",
          CName1: "Work with NGO",
        },
        
      ],
      Fifth: [
        {Sno:"1",
        Mode:"Theory",
        CName1: "Advance Illustration I",
      },

      {Sno:"2",
      Mode:"Theory",
          CName1: "Merchandising",
    },
    {Sno:"3",
    Mode:"Theory/Practical",
          CName1:"1- Construction of Ethenic Wear",
          
          // [ 
          //   {
          //   C1:  "1- Construction of Ethenic Wear",
          // },
          //   {
          //     C1:  "2- Construction of Western Wear",
          //   },
          // ],
  },
  {Sno:"4",
  Mode:"Theory/Practical",
          CName1: "Accessories designing",
},
{Sno:"5",
Mode:"Theory/Practical",
            CName1: "Advance Garment Construction",
},

      ],
        Sixth: [
          {
            Sno:"1",
        Mode:"Theory",
    
            CName1: "Advance  Illustration II",
          },
          {
            Sno:"2",
            Mode:"Theory/Practical",
        CName1: "Garment Construction Mens's wear and Kids Wear",
          },
          {
            Sno:"3",
            Mode:"Theory/Practical",
        CName1: " -Aari Work and Creative Textile and Craft Heritage",
          },
          {
            Sno:"4",
            Mode:"Theory",
        CName1: "Advance Fashion Portfolio",
          },
          {
            Sno:"5",
            Mode:"Theory/Practical",
        CName1: "OJT",
          },
          
        ],
    
  },

 
];

export default CourseDescFashion;
