import icon_cd from "../Images/banner3.jpg";
const CourseDescFashion = [
  {
    id: 1,
    ServiceIcon: icon_cd,
    ServiceName: "B.SC in Fashion Design",
    Duration: "36 Months",
    Eligibility: "10th Grade",
    Slugs: "/fashion-design",
    ServicePara1:
      "During the program, you will develop an in-depth understanding of the tools and techniques which are used in Fashion Designing. You will be interacting with our Subject Matter Experts, who have worked on projects that have been acclaimed both nationally and internationally. ",

    // ServicePara2:
    // " Ask yourself these questions “Do I have a perfect smile?” “Do I have a selfie-friendly smile?” “Does my smile get me compliments galore?.If yes, you are blessed with nature’s best gift. But if you are among those who shy to smile owing to misaligned, crooked, protruding, disjointed, irregular, gapped, stained and discolored teeth, you need to consider a smile makeover and bring back the confidence in your life.",
    // ServicePara3:
    // "With revolutionary technology and expertise, it is very much possible. ",
    // ServicePara4:
    // "OraMax dental clinic , Juhu specializes in smile makeovers to enhance your personality, boost your self-image and confidence and enable you to fall in love with your own smile. OraMax believe that you must love yourself to be able to create lasting impressions on others.",
    First: [
      {
        Sno:"1",
        Mode:"training",
        CName1:"colour Theory" , 
    },
    {
      Sno:"2",
      Mode:"training",
      CName1:"Pattern Making" , 
  },
  {
    Sno:"3",
    Mode:"training",
    CName1:"Embroidery" , 
},
{
  Sno:"4",
  Mode:"training",
  CName1:"Illustration" , 
},
{
  Sno:"5",
  Mode:"training",
  CName1:"Fabric Painting" , 
},
{
  Sno:"6",
  Mode:"training",
  CName1:"History of Indian costume texttile" , 
},
{
  Sno:"7",
  Mode:"training",
  CName1:"Garment Construction" , 
},
{
  Sno:"8",
  Mode:"training",
  CName1:"Computers Designing" , 
},
 ],
    Second: [
     {
      Sno:"8",
      Mode:"training",
      CName1: " Indian Costumes",
     },
     {
      Sno:"8",
      Mode:"training",
      CName1: " Draping",
     },
       { Sno:"8",
       Mode:"training",
       CName1: "Fashion terminology",
      },
        
       {Sno:"8",
       Mode:"training",
        CName1: " Personality Development",
      },
      {Sno:"8",
      Mode:"training",
        CName1: "Grooming",},

        
        {Sno:"8",
        Mode:"training",
          CName1: "Factory Visit",},
        {Sno:"8",
        Mode:"training",
          CName1: "Exhibition",},
        {Sno:"8",
        Mode:"training",
          CName1: " Fashion show",
        },
   
    ],
      Third: [
        {Sno:"1",
        Mode:"training",
        CName1: "Advance Ilustration",
      },
      {      Sno:"2",
        Mode:"training",
          CName1: "Advance Garment Construction",
    },
    {Sno:"3",
    Mode:"training",
          CName1: " International Embroidery",
  },
  {Sno:"4",
  Mode:"training",
            CName1: "Yarn craft",
},
{Sno:"5",
Mode:"training",
            CName1: "Textile World Fashion",
},
{Sno:"6",
Mode:"training",
          CName1: "Draping on Mannequins",
},
{Sno:"7",
Mode:"training",
          CName1: "Computers Designing",
},
{Sno:"8",
Mode:"training",
          CName8: " History of World Costumes ",
        },
      ],
      Fourth: [
        // {
        //   Sno:"1",
        // Mode:"training",
        // },
        {Sno:"1",
        Mode:"training",
          CName1: " Merchandising",
      },
      {
        Sno:"2",
        Mode:"training",
          CName1: "Fashion Retail",
      },
      {Sno:"3",
      Mode:"training",
          CName1: "Khakha Making & Aari work",
    },
  //   {Sno:"5",
  //   Mode:"training",
  // },
  {Sno:"4",
  Mode:"training",
              CName1: "Product Making",
},{Sno:"5",
Mode:"training",
          CName1: "Grooming",
},
{Sno:"6",
Mode:"training",
          CName1: "Factory Visit",
},
{Sno:"7",
Mode:"training",
          CName1: "Exhibition",
},
{Sno:"8",
Mode:"training",
          CName1: "Fashion show",
        },
      ],
      Fifth: [
        {Sno:"1",
        Mode:"training",
        CName1: "World costume",
      },
      {Sno:"2",
      Mode:"training",
          CName1: "Fashion forecast",
    },
    {Sno:"3",
    Mode:"training",
          CName1: "History of Western World Fashion",
  },
  {Sno:"4",
  Mode:"training",
          CName1: "Fashion Theory",
},
{Sno:"5",
Mode:"training",
            CName1: "Garment Construction",
},
{Sno:"6",
Mode:"training",
          CName1: "Surface Omamentation",
},
{Sno:"7",
Mode:"training",
          CName1: "Accessory Designing",
},
         {Sno:"8",
         Mode:"training",
          CName1: "Advance Textile Designing",
},
{Sno:"9",
Mode:"training",
          CName1: " Boutique Management",
        },
      ],
        Sixth: [
          {
            Sno:"1",
        Mode:"training",
    
            CName1: " Computerize Designing",
          },
          {
            Sno:"2",
            Mode:"training",
        CName1: "Costume Designing",
          },
          {
            Sno:"3",
            Mode:"training",
        CName1: " Merchandising",
          },
          {
            Sno:"4",
            Mode:"training",
        CName1: "Product Making",
          },
          {
            Sno:"5",
            Mode:"training",
        CName1: "Personality Development",
          },
          {
            Sno:"6",
            Mode:"training",
        CName1: "Factory Visit",
          },
          {
            Sno:"7",
            Mode:"training",
        CName1: "Exhibition",
          },
          {
            Sno:"8",
            Mode:"training",
        CName1: "Fashion show",
          },
          
        ],
    
  },

  // {
  //   id: 2,
  //   Year: [
  //     {
  //       Heading2: "Second Year",

  //       CName1: "Advance Ilustration",
  //       CName2: "Advance Garment Construction",
  //       CName3: " International Embroidery",
  //       CName4: "Yarn craft",
  //       CName5: "Textile World Fashion",
  //       CName6: "Draping on Mannequins",
  //       CName7: "Computers Designing",
  //       CName8: " History of World Costumes ",
  //     },

  //     {
  //       CName1: " Merchandising",
  //       CName2: "Fashion Retail",
  //       CName3: "Khakha Making & Aari work",
  //       CName4: "Product Making",
  //       CName5: "Grooming",
  //       CName6: "Factory Visit",
  //       CName7: "Exhibition",
  //       CName8: "Fashion show",
  //     },
  //   ],
  // },
  // {
  //   id: 3,

  //   Heading: "Third Year",
  //   Year: [
  //     {
  //       CName1: "World costume",
  //       CName2: "Fashion forecast",
  //       CName3: "History of Western World Fashion",
  //       CName4: "Fashion Theory",
  //       CName5: "Garment Construction",
  //       CName6: "Surface Omamentation",
  //       CName7: "Accessory Designing",
  //       CName8: "Advance Textile Designing",
  //       CName9: " Boutique Management",
  //     },

  //     {
  //       CName1: " Computerize Designing",
  //       CName2: "Costume Designing",
  //       CName3: " Merchandising",
  //       CName4: "Product Making",
  //       CName5: "Personality Development",
  //       CName6: "Factory Visit",
  //       CName7: "Exhibition",
  //       CName8: "Fashion show",
  //     },
  //   ],
  // },
];

export default CourseDescFashion;
